### ISSUE TITLE
create should check and encode the data it stores into addon.xml

### ISSUE THREAD

**Issue by rasjani** [jbeluch/xbmcswift2#27]
When i enter provider in format something like: Foo 'bar' Baz foo@baz.bar , generated addon.xml does not encode the characters to be valid xml which leads atleast the xbmcswift2 execute to throw a xml.etree.ElementTree.ParseError: not well-formed (invalid token) exception ..

**Comment by jbeluch** [comment]
Ah, double quotes are not being escaped properly. Thanks.
