### ISSUE TITLE
context_menu + XBMC.RunPlugin + set_resolved_url does not work

### ISSUE THREAD

**Issue by cancan101** [jbeluch/xbmcswift2#38]
I have added an action to the context menu to call back into the plugin using XBMC.RunPlugin.

This correctly works and I can see the correct route being called. However with the route I am then using set_resolved_url to play a URL. Making his call yields:

ERROR: SetResolvedUrl - called with an invalid handle.

and the video does NOT play.

**Comment by cancan101** [comment]
I set up the context menu using:

``` python
play_url = plugin.url_for(endpoint=..., ...)

item = {
...
'context_menu':[("Play with subs", "XBMC.RunPlugin(%s)" % play_url)],
}
```

**Comment by jbeluch** [comment]
I don't believe you can play a video/call set_resolved_url using RunPlugin since it spins another thread with a handle of -1. Only the main addon thread with handle 0 can play videos. I think. Will try to find out more.

**Comment by dersphere** [comment]
You need to to use the PlayMedia xbmc builtin instead of RunPlugin.

``````
item = {
...
'context_menu':[("Play with subs", "XBMC.PlayMedia(%s)" % play_url)],
}```
``````

**Comment by cancan101** [comment]
I no longer get the  invalid handle. but the video does not play. There is no indication of any issues in the log.

**Comment by dersphere** [comment]
And your play_url may not have a trailing slash when using PlayMedia().

**Comment by cancan101** [comment]
The play_url call seems to work fine. XBMC does in fact call back into the plugin. Once in the plugin, however, calls to set_resolved_url do not seem to have any effect.

**Comment by cancan101** [comment]
I am able to get the video to play using:

``` python
item = {
...
'context_menu':[("Play with subs", "XBMC.PlayMedia(%s)" % play_url)],
}
```

to call into the plugin and then

``` python
ret = plugin.play_video({'path':path,'label':label})
```

within the plugin to play the video.

I used that line rather than 

``` python
ret = plugin.set_resolved_url(path)
```

So far so good. I can use context menu to start video playing. However, if I then call:

``` python
player = xbmc.Player()
while not player.isPlaying():
   time.sleep(1)
player.setSubtitles(subtitle_url)
```

no subtitles are shown.

**Comment by jbeluch** [comment]
See #68.
