### ISSUE TITLE
IOError with Cache

### ISSUE THREAD

**Issue by cancan101** [jbeluch/xbmcswift2#43]
```
23:34:10 T:2844765040   ERROR: Error Type: <type 'exceptions.IOError'>
23:34:10 T:2844765040   ERROR: Error Contents: (2, 'No such file or directory', '/home/xbmc/.xbmc/userdata/addon_data/plugin.video.coursera/.storage/.functions.tmp')
23:34:10 T:2844765040   ERROR: Traceback (most recent call last):
                                              File "/home/xbmc/.xbmc/addons/plugin.video.coursera/addon.py", line 493, in <module>
                                                plugin.run()
                                              File "/home/xbmc/.xbmc/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 318, in run
                                                return self._dispatch(self.request.path)
                                              File "/home/xbmc/.xbmc/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 302, in _dispatch
                                                listitems = self.finish(listitems)
                                              File "/home/xbmc/.xbmc/addons/script.module.xbmcswift2/lib/xbmcswift2/xbmcmixin.py", line 380, in finish
                                                storage.close()
                                              File "/home/xbmc/.xbmc/addons/script.module.xbmcswift2/lib/xbmcswift2/storage.py", line 69, in close
                                                self.sync()
                                              File "/home/xbmc/.xbmc/addons/script.module.xbmcswift2/lib/xbmcswift2/storage.py", line 63, in sync
                                                shutil.move(tempname, self.filename)    # atomic commit
                                              File "/usr/lib/python2.7/shutil.py", line 298, in move
                                                copy2(src, real_dst)
                                              File "/usr/lib/python2.7/shutil.py", line 127, in copy2
                                                copyfile(src, dst)
                                              File "/usr/lib/python2.7/shutil.py", line 81, in copyfile
                                                with open(src, 'rb') as fsrc:
                                            IOError: (2, 'No such file or directory', '/home/xbmc/.xbmc/userdata/addon_data/plugin.video.coursera/.storage/.functions.tmp')
```

**Comment by jbeluch** [comment]
Will try to debug with your addon. Is this traceback from the CLI or within XBMC? How can I reproduce it?

**Comment by cancan101** [comment]
That is from within XBMC.

**Comment by jbeluch** [comment]
- Is this the first time you tried to run, or was it working previously?
- Does `/home/xbmc/.xbmc/userdata/addon_data/plugin.video.coursera/.storage/` exist?
- In XBMC, were you initially loading your addon from the list of addons (the url of '/') or were you deep down in the hierarchy (and if so, what url)?

**Comment by jbeluch** [comment]
I think there's an issue with the `cached_route` decorator when using it multiple times on a view. Try using just the regular route decorator instead of the cached_route here https://github.com/cancan101/xbmc-coursera/blob/master/addon.py#L112 and see if error goes away.

**Comment by cancan101** [comment]
This is not the first time that I was using this plugin; I have been using
it for a while.

alex@acer:~$ ls
/home/xbmc/.xbmc/userdata/addon_data/plugin.video.coursera/.storage/ -al
total 1636
drwxrwxr-x 2 xbmc xbmc    4096 2012-11-27 23:52 .
drwxrwxr-x 3 xbmc xbmc    4096 2012-11-10 16:48 ..
-rw-rw-r-- 1 xbmc xbmc    4046 2012-11-27 23:52 agrothberg@gmail.com
-rw-rw-r-- 1 xbmc xbmc 1657144 2012-11-27 23:52 .functions
-rw-rw-r-- 1 xbmc xbmc       4 2012-11-27 22:36 main

I was deep down in the hierarchy:
I think it occurred here:

@plugin.route('/courses/<courseShortName>/lecture/<lecture_id>/')
def playLecture(courseShortName, lecture_id):

I have been at this level many time before, however.

I also think that I have seen an issue like this in the past. I thought I
had emailed you a while ago.

**Comment by cancan101** [comment]
It looks like i never sent the email from the previous time this happened.

Here is one example:

18:19:48 T:2898865008  NOTICE: [xbmcswift2] Request for "/classes/wh1300/"
matches rule for function "listCourses"
18:19:48 T:2890472304  NOTICE: [xbmcswift2] Request for "/clearcache/"
matches rule for function "clearcache"
18:19:48 T:2890472304  NOTICE: [plugin.video.coursera] clearing cache
18:19:49 T:2898865008   ERROR: Error Type: <type 'exceptions.IOError'>
18:19:49 T:2898865008   ERROR: Error Contents: (2, 'No such file or
directory',
'/home/xbmc/.xbmc/userdata/addon_data/plugin.video.coursera/.storage/.functions.tmp')
18:19:49 T:2898865008   ERROR: Traceback (most recent call last):
                                              File
"/home/xbmc/.xbmc/addons/plugin.video.coursera/addon.py", line 411, in
<module>
                                                plugin.run()
                                              File
"/home/xbmc/.xbmc/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py",
line 311, in run
                                                return
self._dispatch(self.request.path)
                                              File
"/home/xbmc/.xbmc/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py",
line 295, in _dispatch
                                                listitems =
self.finish(listitems)
                                              File
"/home/xbmc/.xbmc/addons/script.module.xbmcswift2/lib/xbmcswift2/xbmcmixin.py",
line 363, in finish
                                                storage.close()
                                              File
"/home/xbmc/.xbmc/addons/script.module.xbmcswift2/lib/xbmcswift2/storage.py",
line 66, in close
                                                self.sync()
                                              File
"/home/xbmc/.xbmc/addons/script.module.xbmcswift2/lib/xbmcswift2/storage.py",
line 60, in sync
                                                shutil.move(tempname,
self.filename)    # atomic commit
                                              File
"/usr/lib/python2.7/shutil.py", line 298, in move
                                                copy2(src, real_dst)
                                              File
"/usr/lib/python2.7/shutil.py", line 127, in copy2
                                                copyfile(src, dst)
                                              File
"/usr/lib/python2.7/shutil.py", line 81, in copyfile
                                                with open(src, 'rb') as
fsrc:
                                            IOError: (2, 'No such file or
directory',
'/home/xbmc/.xbmc/userdata/addon_data/plugin.video.coursera/.storage/.functions.tmp')

**Comment by cancan101** [comment]
I should add, this issue happens only sporadically

**Comment by cancan101** [comment]
The above suggestion to remove the duplicate `cached_route` decorator did not work.

I can replicate the issue (somewhat):

1) clear cache:

``` python
    username = plugin.get_setting('username')
    if username is not None and username != "":
        user_cache = plugin.get_storage(username, file_format='json')
        user_cache.clear()
        user_cache.sync()

    func_cache = plugin.get_storage('.functions', file_format='pickle')
    func_cache.clear()
    func_cache.sync()

    main_cache = plugin.get_storage('main', file_format='pickle')
    main_cache.clear()
    main_cache.sync()
```

2)
call into `playLecture(courseShortName, lecture_id)`

**Comment by jbeluch** [comment]
The current storage solution isn't really safe for multi-threadedness. Working on a better storage solution that should avoid these problems. I'm gonna close this issue for now. If this is still causing you headaches reopen the issue and I'll spend more time looking into it.
