### ISSUE TITLE
CLI mode doesn't respect update_listing=True to plugin.finish

### ISSUE THREAD

**Issue by jbeluch** [jbeluch/xbmcswift2#45]
current url shouldn't go on the stack if update_listing=True

**Comment by jbeluch** [comment]
@ulion didn't use your PR because you had a bunch of other changes, but used your solution :)

**Comment by ulion** [comment]
Oh, I didn't split it out because it was tied with my cli context menu commit. Now I can rebase on your new commit:)

**Comment by jbeluch** [comment]
Cool, yeah that's what I figured. Will welcome the context menu stuff once you can rebase it.
