### ISSUE TITLE
XBMC.RunPlugin(%s) wrapper

### ISSUE THREAD

**Issue by jbeluch** [jbeluch/xbmcswift2#48]
Can also tie it in with complete context_menu tuple

```
def context_item_run_plugin(text, url)
```

**Comment by dersphere** [comment]
Please note that there are two different calls from context menu possible.
Described here: https://github.com/jbeluch/xbmcswift2/issues/37#issuecomment-11631594

**Comment by tamland** [comment]
There's also `RunScript` and `RunAddon`. To have the ability to run scripts as well would be great. I always though `RunPlugin` was for opening new virtual folders and `RunScript` was for background actions, but from what you say in #37 @dersphere, I'm not sure anymore. `RunAddon` I have no idea what does

**Comment by dersphere** [comment]
From my understanding/Like I use it:
`RunScript()` is for script execution like `RunScript(/home/sphere/clean_db.py)`
`RunAddon()` is for starting an addon in its root like `RunAddon(script.game.whatthemovie)`
`RunPlugin()` is for calling an plugin to do some background action (Doesnt get a handle)
`XBMC.Container.Update()` is for changing the actual container to the given one (Does get a handle)

What a mess ;)

**Comment by jbeluch** [comment]
So, I'm thinking I'll just create xbmcswift2.actions, which will contain functions for the above 4 builtins. Then the context menu items will look like:

``` python
from xbmcswift2 import actions
context_menu = [
    ('Open Youtube Addon', actions.run_addon('plugin.video.youtube')),
    ('Do some background action', actions.run_plugin(plugin.url_for('background_action')))
]
```

@dersphere @takoi thoughts?

**Comment by dersphere** [comment]
ok.

Btw, I had something in mind like:

``` python
context_menu = [
    ('Open Youtube Addon', plugin.url_for('plugin.video.youtube', method='run_addon')),
    ('Do some background action', plugin.url_for('background_action', method='update_container'))
]
```

**Comment by jbeluch** [comment]
Hmm. The problems with adding args to url_for are:
1. Any named args can then not be used for URL building/routes (e.g. `method`).
2. Each of the above builtins have different numbers and names of arguments.

If we have functions for each builtin, then its clear what args are required/optional.

**Comment by dersphere** [comment]
You are right, your is better :)

**Comment by tamland** [comment]
.. but don't name that action `run_plugin`. Clearly the naming scheme here is legacy. 

`RunScript`: i don't think this is even needed. RunPlugin does the same. Only difference I can see is that RunScript can in addition run arbitrary scripts in a very unportable way.
`RunAddon`: not sure why a plugin would need this either. I think it's mostly mean for skins.
`XBMC.Container.Update`: should be "run plugin". Because that's what it's for; running plugins.
`RunPlugin`: should be run script, function or something like that.
