### ISSUE TITLE
Document update_listing and cache_to_disc parameters

### ISSUE THREAD

**Issue by rexxars** [jbeluch/xbmcswift2#51]
I struggled with the history being funky when I tried to implement pagination. Found the solution by looking at the rofl.to plugin source, but it took me a while.

Seeing a lot of goodies in the documentation that are only mentioned but not documented. Would contribute, but I don't feel confident enough with xbmcswift yet.

On an unrelated note; great project :-)

**Comment by jbeluch** [comment]
This should be fixed, reopening :)
