### ISSUE TITLE
Request: Mock xbmcgui.Window

### ISSUE THREAD

**Issue by rexxars** [jbeluch/xbmcswift2#52]
I need to add some statistics methods to my plugin, and will need the width and height of XBMC. This is provided through the xbmcgui.Window class (getWidth() / getHeight()).

It would be great if there was a way to use this with xbmcswift2. For now I've implemented the class in xbmcgui.py to just return static values, but I'm unsure if this is the right way to do it.

**Comment by jbeluch** [comment]
Hi, thanks for the input, although I'm not sure exactly what you're asking. You want to mock the getHeight and getWidth methods for CLI mode to return arbitrary int values? Currently those methods when called in CLI mode will return generic mock objects.

**Comment by jbeluch** [comment]
@rexxars, do you have more info on what behavior you'd like for this issue? Do you just want it to always return 1920 or 1280? Do you need something more sophisticated?

**Comment by jbeluch** [comment]
Feel free to reopen if you have more info.
