### ISSUE TITLE
subtitles helper

### ISSUE THREAD

**Issue by jbeluch** [jbeluch/xbmcswift2#53]

**Comment by cancan101** [comment]
It looks like the Ted Talks plugin does subtitles the same way: https://github.com/moreginger/xbmc-plugin.video.ted.talks/blob/eden/resources/lib/ted_talks.py#L77 as does the YouTube Plugin: http://code.google.com/p/youtubexbmc/source/browse/trunk/YouTubePlayer.py#293

**Comment by jbeluch** [comment]
Cool, thanks for doing the hard work :) Will get to this soon.
