### ISSUE TITLE
set_resolved_url should take a list item, or url optionally 

### ISSUE THREAD

**Issue by jbeluch** [jbeluch/xbmcswift2#54]

**Comment by ulion** [comment]
I found this problem also days ago, I did not write a patch since the xbmcswift is auto installed by xbmc and I can not change it, so I wrote a patch for addons to use. set mimetype is important because it can speed up the progress and some server did not send correct mimetype and addon can set correct mime-type.

``` python
def patch_the_plugin():
    import inspect
    if len(inspect.getargspec(xbmcswift2.Plugin.set_resolved_url).args) == 2:
        def set_resolved_url(self, url, mimetype=None):
            if type(url) in [str, unicode]:
                item = xbmcswift2.ListItem(path=url)
            elif type(url) == dict:
                item = xbmcswift2.ListItem.from_dict(**url)
            else:
                raise 'wrong url set for set_resolved_url()'
            if mimetype:
                item.set_property('mimetype', mimetype)
            item.set_played(True)
            xbmcswift2.xbmcplugin.setResolvedUrl(self.handle, True, item.as_xbmc_listitem())
            return [item]
        xbmcswift2.Plugin.set_resolved_url = set_resolved_url
```

**Comment by jbeluch** [comment]
Added in dev branch, 05da9dc7756d32a76f903cc9316cdadeccf47c2a

**Comment by edevil** [comment]
So, is there a way so set the mimetype? set_resolved_url takes an item, but ListItem.from_dict does not accept a "mimetype" keyword argument.

**Comment by ulion** [comment]
item.set_property('mimetype', mimetype) after from_dict
or set the mimetype in the 'properties' param of the from_dict.

**Comment by edevil** [comment]
Thank you!
