### ISSUE TITLE
Support chinese keyboard input by the Plugin's keyboard method

### ISSUE THREAD

**Issue by ulion** [jbeluch/xbmcswift2#55]
the Chinese Keyboard addon (http://forum.xbmc.org/showthread.php?tid=98194) is used in many chinese addons, for using it together with xbmcswift2, I wrote an addon side patch for xbmcswift, here it is:

``` python
def patch_the_plugin():
    import inspect
    if len(inspect.getargspec(xbmcswift2.Plugin.keyboard).args) == 4:
        try:
            import ChineseKeyboard
            def keyboard(self, default=None, heading=None, hidden=False, prefered_lang='en'):
                if heading is None:
                    heading = self.addon.getAddonInfo('name')
                if default is None:
                    default = ''
                if not hidden and prefered_lang.lower() in ['cn', 'zh-cn']:
                    keyboard = ChineseKeyboard.Keyboard(default, heading)
                else:
                    keyboard = xbmcswift2.xbmc.Keyboard(default, heading, hidden)
                keyboard.doModal()
                if keyboard.isConfirmed():
                    return keyboard.getText()
            xbmcswift2.Plugin.keyboard = keyboard
        except:
            pass
```

**Comment by jbeluch** [comment]
I don't want to create a dependency on the ChinseKeyboard addon, however, I can perhaps add an optional argument that takes a Keyboard instance. The default would value would be `xbmc.Keyboard`, but you can import ChineseKeyboard and pass `ChineseKeyboard.Keyboard` if you like.

Does that work?

**Comment by ulion** [comment]
it's ok, the Keyboard is not so important, I can inject by my patch to use it anyway. you can forget this topic.
