### ISSUE TITLE
add xbmcvfs to mockxbmc

### ISSUE THREAD

**Issue by dersphere** [jbeluch/xbmcswift2#58]
See http://mirrors.xbmc.org/docs/python-docs/xbmcvfs.html for docs.

The advantage of xbmcvfs over os or shutil is that xbmcvfs can manage all xbmc virtual file systems and sources (like smb-shares).

**Comment by jbeluch** [comment]
Is it enough to simply add the ability to import xbmcvfs from xbmcswift2? Or do you want the functionality replicated for CLI use?

**Comment by dersphere** [comment]
The ability to import it would be enough for now.

**Comment by jbeluch** [comment]
It seems I already had a mock xbmcvfs in the **init**.py file. However, I added a blank .py file to keep it the same as the other mock modules (db3efe4b86e199de35c335ec596692d35d53cb99).
