### ISSUE TITLE
Exception Trapping Decorator

### ISSUE THREAD

**Issue by cancan101** [jbeluch/xbmcswift2#64]
Create a decorator (in addition to or instead of the plugin.route decorator) that catches a specified exception, calls plugin.notify and then returns an empty list.

**Comment by jbeluch** [comment]
I think this is better implemented as code in your addon. Perhaps:

```
# addon.py
if __name__ == '__main__':
    try:
        plugin.run()
    except MySpecialException:
        plugin.notify('An error occured. Please notify the addon author.')

```
