### ISSUE TITLE
add info to documentation/website about traling slash urls

### ISSUE THREAD

**Issue by dersphere** [jbeluch/xbmcswift2#71]
It should be suggested to have the views which provide a list of listitems end with a slash and the views which return via set_resolved_url end without a trailing slash.

Else the xbmc internal PlayMedia()-method which is used e.g. on favorites, won't work correctly.

**Comment by ulion** [comment]
another problem: 
some xbmc module such as filemanager, will remove the tailing slash and then call plugin to list dir items, it's unhappy to xbmcswift2 depended addons.
so currently for this problem, my workaround is patch xbmcswift2 to let the tailing slash optional when resolving the input plugin url, it's harmless, and works.

**Comment by dersphere** [comment]
Interesting.

Changing swift to match URLs to views with and without trailing slashes sounds like a good idea to me, @jbeluch?
