### ISSUE TITLE
endOfDirectory auto-call preventing normal use

### ISSUE THREAD

**Issue by tamland** [jbeluch/xbmcswift2#72]
I'm trying to upgrade an addon to xbmcswift2 it's introducing bugs because it's calling the endOfDirectory function no matter what. It didn't do this in xbmcswift1. I think there's already been multiple issues reported related to this. Basically, by always calling this function you prevent all calls to the addon from doing anything but listing a virtual directory. For instance how could you implement the basic cancelable search functionality like [this](https://github.com/takoi/xbmc-addon-nrk/blob/master/default.py#L115)? Looking at a few other addons, e.g @dersphere [here](https://github.com/dersphere/plugin.video.itunes_podcasts/blob/master/addon.py#L144) (cancel doesn't work), I don't think you can with the current api.

How can you even do any kind of dialogs, gui and other kind of actions with xbmcswift2 if it's calling endOfDirectory? Liked the old behavior much better.

**Comment by ulion** [comment]
for your purpose, just call plugin.finish(succeeded=False) for non-playable plugin call, and plugin.set_resolved_url(succeeded=False) (this will come soon) for playable plugin call.

**Comment by tamland** [comment]
That's.. a hack too isn't it?. What did it do in xbmcswift1 exactly and what was wrong with that behavior? Never caused any trouble before. I don't get the whole force calling endOfDirectory procedure..

**Comment by jbeluch** [comment]
In xbmcswift1, you had to explicitly call `add_items`, which would call endOfDirectory. Obviously in swift2 we can return lists of dicts, so perhaps we need to come up witha  solution to ensure it doesn't called when not necessary.

**Comment by tamland** [comment]
Surely you can skip the call if the function is returning None, or not a list. People would normally return an empty list if they want an empty directory right?

**Comment by jbeluch** [comment]
@takoi, I merged @ulion's PR to call plugin.finish(succeeded=False) if None is returned from a view. Does this solve your problem?

**Comment by tamland** [comment]
@jbeluch well technically it doesn't "not succeed", but I'm not sure it will make a difference. The xbmc api docs doesn't specify what succeeded=False really means.

Also, if you don't have any future plans for the api, I think it would be better to just check for lists. That would make it easier to slap the annotation onto existing function without the plugin automatically failing from type errors.

**Comment by jbeluch** [comment]
@takoi, I think you are right in that it doesn't make a difference. I tested an addon without calling endOfDirectory (basically returning None) and the same addon calling with suceeded=False. The log output appears the same, both output "Error" log messages.

In regards to the type errors, do you mean that some of your view functions return things other than lists or None? You get TypeErrors from xbmcswift2 code?

**Comment by tamland** [comment]
I mean: swift will always throw some exception and fail if the view function is returning something else than the expected list. I currently don't do that in my addons but I can see how people might, to make functions reusable, not having to add new special functions that don't return so it doesn't conflict.

**Comment by ulion** [comment]
report fail will let xbmc continue its work at once
do nothing will let xbmc continue its work after python script exit.
both let xbmc think the dir listing or url resolving failed, since only these two type calls with handle ge 0.
but, if handle ge 0, the view function is reusable, and it does not return a list, what does the function do?
is there an example code? does the function called set_resolve_url/setResolvedUrl and finally return non-list? this condition happens because current set_resolve_url did not set endOfDirectory so it will auto-call finish then report type error, it's a bug of swift2 and should be fixed.
