### ISSUE TITLE
xbmc should decide the default player core

### ISSUE THREAD

**Issue by tamland** [jbeluch/xbmcswift2#73]
Default in xbmcswift is to [setting it to dvdplayer](https://github.com/jbeluch/xbmcswift2/blob/develop/xbmcswift2/xbmcmixin.py#L318). Default behavior should be to let xbmc handle that, i.e by not passing the player argument if it isn't set.

**Comment by ulion** [comment]
I also agree to use the AUTO core as the default.

**Comment by jbeluch** [comment]
It seems not passing the player argument is equivalent to passing AUTO, so simpler to remove the default arg.

**Comment by jbeluch** [comment]
Fixed 04131a6b2748a449202901fbec97479799637351
