### ISSUE TITLE
catch corrupted storage exception / fix reason for corrupted storage

### ISSUE THREAD

**Issue by dersphere** [jbeluch/xbmcswift2#85]
Like discussed on IRC, we need a way to pass the situation where the storage file gots corrupted. Example log: http://xbmclogs.com/show.php?id=30424 (Line 235+).

The reason for the corrupted file is, I believe, a race condition on slow execution like on a RPI.

**Comment by ulion** [comment]
it's better to save file to a new unique filename then rename to the final name, it's better move the original one into a backup name also, when corrupted, can try the backup one first, if still failed, load an empty one instead of fail.
