### ISSUE TITLE
Frodo is out, but xbmcswift in xbmc official repository need be updated else always fails

### ISSUE THREAD

**Issue by ulion** [jbeluch/xbmcswift2#86]
because the handle == 0 check, most addons using xbmcswift will fail in frodo.

**Comment by dersphere** [comment]
The Pull Request into the official Repository for Frodo was opened 9 hours ago.

**Comment by ulion** [comment]
good news, although frodo missed some good feature I desired, but I'm glad to work on the git version xbmc and fix anything need be fixed there.

**Comment by dersphere** [comment]
Yes, I follow the xbmc repository and saw your PRs, good job :)

**Comment by jbeluch** [comment]
It was just pulled just now. I released a hotfix with just @ulion's commit for now. Will try to get the other stuff finished in a week or so.
